apiVersion: 1

datasources:
  - name: ClickHouse
    uid: cachette-clickhouse
    type: grafana-clickhouse-datasource
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      secure: false
      username: cachette
      defaultDatabase: bench
      defaultTable: rows
    secureJsonData:
      password: cachette

  - name: Loki
    uid: cachette-loki
    type: loki
    access: proxy
    url: http://loki:3100
