#!/usr/bin/env python3
"""Check that the built reference carries the prose of the compiled module.

ADR-0107 D1 says the published Python reference is generated by an import of
the compiled extension module. ADR-0107 D4 says the documentation job builds
the extension first, and fails rather than publishes when the import does not
happen.

Nothing in a documentation build fails on its own when the import does not
happen. Research report 19 section 4.2 measured it against this repository: the
same site built with module inspection turned off fell back to the type stub,
lost every method summary, and reported no error. That page looks complete. It
carries signatures and no prose.

This script is the guard. It runs in two modes.

  --import-only   Import the compiled module and collect the docstrings. It
                  fails when the import fails. The documentation job runs this
                  before the site build, so the job stops early.

  a site path     Import the module, then read every page under the given
                  directory. Each first line of prose that the import found
                  must appear on a page. It fails when one does not.

**The expected text is derived and never written here.** The script takes it
from the module that the import creates, so this file holds no copy of any
docstring. A second declaration site for the prose is the defect shape this
project names first in its own rule.

The script reports, without failing, every public member that carries no
docstring. ADR-0107 says in its own consequences that such a member publishes
with no prose and that nothing fails. Writing that prose is separate work, and
it is work in the bindings crate.

Exit 0 when every test passes, 1 otherwise. No dependency beyond the standard
library and the package under test.

Usage:

    python3 scripts/check_reference.py --import-only
    python3 scripts/check_reference.py target/site
"""

from __future__ import annotations

import argparse
import html
import inspect
import re
import sys
from dataclasses import dataclass
from pathlib import Path

MODULE_NAME = "cachette._core"

# A tag, a footnote marker, and the two emphasis characters that a renderer
# turns into an element rather than into text.
TAG = re.compile(r"<[^>]+>")
FOOTNOTE_MARKER = re.compile(r"\[\^[^\]]+\]")
EMPHASIS = re.compile(r"[`*]")
WHITESPACE = re.compile(r"\s+")
# A renderer turns an inline code span into an element. Removing the tag
# leaves a space in front of the punctuation that follows it, and the
# prose that the import carries holds no such space.
PUNCTUATION_SPACE = re.compile(r"\s+([.,;:!?)\]])")


@dataclass(frozen=True)
class Member:
    """One public member of the compiled module, and its first line of prose."""

    path: str
    summary: str


def normalise(text: str) -> str:
    """Reduce rendered text and source prose to one comparable form."""
    text = html.unescape(TAG.sub(" ", text))
    text = FOOTNOTE_MARKER.sub(" ", text)
    text = EMPHASIS.sub("", text)
    text = WHITESPACE.sub(" ", text)
    return PUNCTUATION_SPACE.sub(r"\1", text).strip()


def summary_of(obj: object) -> str:
    """Return the first line of the docstring of an object, or the empty string."""
    doc = inspect.getdoc(obj)
    if not doc:
        return ""
    return doc.strip().splitlines()[0].strip()


def collect(module: object) -> tuple[list[Member], list[str]]:
    """Collect the public members of the module with prose, and those without.

    The walk reads the module and then each class the module holds. It reads
    the members a class declares itself, not the members it inherits, because
    an inherited member belongs to the class that declares it.
    """
    with_prose: list[Member] = []
    without: list[str] = []

    for name in sorted(n for n in dir(module) if not n.startswith("_")):
        obj = getattr(module, name)
        path = f"{MODULE_NAME}.{name}"
        summary = summary_of(obj)
        if summary:
            with_prose.append(Member(path, summary))
        else:
            without.append(path)

        if not inspect.isclass(obj):
            continue

        for attr in sorted(a for a in vars(obj) if not a.startswith("_")):
            member = inspect.getattr_static(obj, attr)
            if isinstance(member, staticmethod | classmethod):
                # The wrapper carries the prose of the wrapper type. The
                # function it wraps carries the prose of the member.
                member = member.__func__
            member_path = f"{path}.{attr}"
            member_summary = summary_of(member)
            if member_summary:
                with_prose.append(Member(member_path, member_summary))
            else:
                without.append(member_path)

    return with_prose, without


def read_site(site: Path) -> str:
    """Return the rendered text of every page under a built site."""
    pages = sorted(site.rglob("*.html"))
    if not pages:
        raise SystemExit(f"the built site holds no page: {site}")
    return " ".join(normalise(page.read_text(encoding="utf-8")) for page in pages)


def main() -> int:
    """Run the check and report."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "site",
        nargs="?",
        help="the directory that holds the built site",
    )
    parser.add_argument(
        "--import-only",
        action="store_true",
        help="import the module and report, without reading a site",
    )
    args = parser.parse_args()

    try:
        module = __import__(MODULE_NAME, fromlist=["_core"])
    except ImportError as error:
        print(f"FAIL import: the build cannot import {MODULE_NAME}: {error}")
        print("ADR-0107 D4: the job builds the extension before it builds the site.")
        return 1

    with_prose, without = collect(module)
    print(f"{MODULE_NAME}: {len(with_prose)} members with prose, {len(without)} without")

    if not with_prose:
        print(f"FAIL prose: the import of {MODULE_NAME} found no docstring at all")
        return 1

    if without:
        print("note: these public members carry no prose, and nothing fails on it")
        for path in without:
            print(f"  {path}")

    if args.import_only:
        return 0

    if args.site is None:
        parser.error("give a site directory, or --import-only")

    rendered = read_site(Path(args.site))
    missing = [m for m in with_prose if normalise(m.summary) not in rendered]

    if missing:
        print(f"FAIL prose: {len(missing)} members carry prose that no page holds")
        for member in missing:
            print(f"  {member.path}: {member.summary}")
        print(
            "ADR-0107 D1: the reference comes from an import of the compiled "
            "module. A build that reaches the type stub instead publishes "
            "signatures and no prose, and it reports no error."
        )
        return 1

    print(f"every one of the {len(with_prose)} summaries reached the site")
    return 0


if __name__ == "__main__":
    sys.exit(main())
